---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flux-helm-tls-ca-config
  namespace: flux
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIE6jCCAtKgAwIBAgIUQl7FDx/Hrd6WOtMVgTYZC3E9pn4wDQYJKoZIhvcNAQEN
    BQAwDTELMAkGA1UEAxMCQ0EwHhcNMTkxMTE5MTc0NjAwWhcNMjQxMTE3MTc0NjAw
    WjANMQswCQYDVQQDEwJDQTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIB
    ALlPuWKztV65ZgYu9gpkdAMQ1Nr3JJWbcCdDD8YCQup376uS5sRTVfj1xPIMzBWI
    l4DF2Idrma1BOQREEdB/L73ZJ0CrJPNSaRJaiLUuqZ73/gJJOvrJGNoCryflsH4Y
    y2ZF0et1WsF5BF4PMazHGp/Hy0v3FwjyX2YHDu7XofxXE/nBitHhNsA81ok12Z4s
    jKrAeUug5406V5GPUWSSIWg3YYUlLIwtqDevkrK5twA9X8LeAy+aN40ijhk8tvAW
    AUq4ILY/scCYY8ruabG7IwWOdhPJI212gBLg255QYBwB78Y5IErZAvFHzdT30Ppu
    YS5/5i1D0ywDHhCeh4hYC1a9kIi5vv7rUiDVmvSgv1EA9mGO/5SDNp3m1J//FdT3
    Chqm2Ks5Jikl27YEDlySZV4vMGmcAlLpt7xU5j5ft2gNN+OH6nYZaK/XuGMhK47T
    hDgaby6SlkxiaNhRP5bv6C6SjlWerbihF7JzzuZIppF5+bHBo98SU2OoOMeQzR2h
    Fdv5bmoXKE+TUZhelrpenabNmr9EU9mMMrb51GIk67AlYhWEw8bTDYT4CWqrHFJW
    KH5NMeC1GlTiuuxyy7Na5pU0clUU+ixUjzjbk741frUHpKCl+osuHzMvJeuUlYfv
    Ex8Z9ku+gDPYemaUVJnIyimmF7b3uFRoP/bRocAQHIqDAgMBAAGjQjBAMA4GA1Ud
    DwEB/wQEAwIBBjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTRa6A7+ZnIcd+Q
    kmnedEC8pcxRYjANBgkqhkiG9w0BAQ0FAAOCAgEAD3ODBzi0yVoixt3MdAYGFKNW
    JCMzFZRgMtCGL2hWq+BENrmZ6q4+6sqHrdvMc6a6sVzg0r9V2I9NupyjMJRLgkuH
    SskHXXWMfQdv2C5izRnDlQNss+3KbB9KkvTonWfOS/YzsW8YpilwPjtVgxNTqWdx
    Ty5D86u/4olN+VJOCbu6UgPfJbDZgSUVrFBUeuxo7MogLwqA6XUoCMDNgmWX2Cmq
    ZkvUjMSF73m0toIQ8pJ8Xuavq6SdNXt30X9TGl6O0Jn57aVXeq10aThi5DHPrBz8
    gT2C8CCkMmHNcoTx+T6PY1Ws0nddZ2UW161QXvqIE7uQzbBs4nl/BtVt63olwUrA
    Iopr5PIqpzkKJXNZhAfCPHhm1tVFj6e0L7N3E3XrBN5dea3uYmeSdu+xTjWU2Bof
    L+jS41WMt3Xq6OH35nmSQjXUVKMZBmaCvxOchGRzrfv1cVB2bmHJLQ4GOshBGeg1
    wSLQpFsuuQNoQwgWxy/9Q2H/5nwlmgvUEXXrOpw+O0PNazRlzkTD/bUv1RFkGpWZ
    NFu8iWdJVGSCNUKP38Hm8+tDFZQoKvDIR+lwazO9h0cWUEYeZ/WJi2eP5x8iyz0i
    oMNmqQUAEpRQIVNHmZ3rsM7TEKcqLURXKWERMMnSIA7L1K1QerRWsW+fomcTOcvH
    /OFTEzUa1TAq6QW91rI=
    -----END CERTIFICATE-----
    
